version: '3'

networks: 
  default: 
    external: 
      name: external-example

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: superdupersecretpassword
      MYSQL_USER: alcali
      MYSQL_PASSWORD: alcali
    volumes:
      - ./docker/sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  ldap-server:
    image: osixia/openldap:1.3.0
    restart: always
    ports:
      - "389:389"
      - "636:636"
  # phpldapadmin:
  #   image: osixia/phpldapadmin:latest
  #   # container_name: phpldapadmin
  #   environment:
  #     PHPLDAPADMIN_LDAP_HOSTS: "ldap-server"
  #     PHPLDAPADMIN_HTTPS: "false"
  #   ports:
  #     - "8081:80"
  #   depends_on:
  #     - ldap-server
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
      args:
        USER_ID: ${USER_ID:-1000}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/alcali/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ldap-server
    env_file:
      - env.test
  master:
    build:
      context: ./docker
      dockerfile: Dockerfile-master
    command: honcho start
    depends_on:
      - web
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - "8080:8080"
  minion:
    build:
      context: ./docker
      dockerfile: Dockerfile-minion
    command: salt-minion -l info
    depends_on:
      - master
      - ldap-server
